FROM docker.io/yottadb/yottadb-base
ENV FLASK_APP=index
ENV FLASK_ENV=development
COPY index.py /tmp/index.py
COPY ukpostcodes1.csv  /tmp/ukpostcodes1.csv
COPY pcode.m /tmp/pcode.m  
SHELL ["/bin/bash", "-c"] 
RUN apt-get update && \
    apt-get install -y python3 python3-pip python3-dev python3-setuptools libffi-dev && \
    pip3 install flask && \
    /opt/yottadb/current/ydb && \
    cp /tmp/pcode.m /data/r && \
    mkdir /home/pcode && \
    cp /tmp/ukpostcodes1.csv /home/pcode && \
    cp /tmp/index.py /home/pcode && \
    /opt/yottadb/current/ydb -run 'START^pcode' && \
    source /opt/yottadb/current/ydb_env_set && \
    pip install yottadb && \
    rm /tmp/index.py && \
    rm /tmp/pcode.m && \
    rm /tmp/ukpostcodes1.csv && \
    rm /home/pcode/ukpostcodes1.csv
WORKDIR /home/pcode
ENTRYPOINT /bin/bash -c 'source /opt/yottadb/current/ydb_env_set && flask run --host=0.0.0.0'
